name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches:
      - vue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # O la versión de Node.js que uses

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run generate # O el comando que uses para generar tu proyecto

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # O la carpeta de salida de tu proyecto
